server:
  port: 8882
spring:
  application:
    name: nuggets-auth-service

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        username: nacos
        password: nacoss
        context-path: /nacos
        server-addr: 127.0.0.1:8848
  datasource:
    password: 12345678
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nuggets-pro?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
