server:
  port: 8881
spring:
  application:
    name: nuggets-gateway-service

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        username: nacos
        password: nacos
        context-path: /nacos
        server-addr: 127.0.0.1:8848
    # 配置跨域
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]': # 匹配所有请求
#            allowedOrigins: "*" # 跨域处理 允许所有的域
#            allowedMethods: # 支持的方法
#              - GET
#              - POST
#              - PUT
#              - DELETE
      routes:
        - id: xxx
          uri: lb://xxx
          predicates:
            - Path=/xxx/**
          filters:
            - StripPrefix= 1
  config:
    import: nacos:nacos-config-example.properties?refresh=true

